services:
  board-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      DB_HOST: "board-db"
      DB_PORT: "5432"
      DB_NAME: "dev_db"
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"

  board-db:
    build:
      context: ./development/db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./development/data/postgres:/var/lib/postgresql/data