name: Deploy frontend

on:
  release:
    tags:
      - 'frontend/**'
    types:
      - released
    branches:
      - release/**
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy to bucket
        working-directory: ${{env.working-directory}}
        run: aws s3 sync s3://${{vars.DEPLOY_BUCKET}} .
