name: Frontend release

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - release/**
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the application'
        required: true
        default: 'latest'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: set-version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Install jq
        if: github.event.inputs.version == ''
        run: sudo apt-get install jq

      - name: Get version from package.json
        working-directory: ${{env.working-directory}}
        id: get_version
        if: github.event.inputs.version == ''
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version: $VERSION"
          echo "::set-output name=result::$VERSION"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy to bucket
        run: echo "deploy to s3 bucket"

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: frontend/${{ env.VERSION }}
          prerelease: ${{ github.ref != 'refs/heads/master' }}
          title: "${{ github.event.repository.name }} Frontend v${{ env.VERSION }}"